### ISSUE TITLE
Need to use JsStore in react without webpack.

### ISSUE THREAD

**Issue by pooja-chhabriya** [ujjwalguptaofficial/jsstore-examples#23]
I am trying to add JsStore in my react app but getting error as jsstore worker is not defined. How to setup Jsstore worker in react without using webpack? I also tried directly passing the path of jsstore worker to new Worker but its giving an error as "Uncaught SyntaxError: Unexpected token '<'".

**Comment by ujjwalguptaofficial** [comment]
Hi

Use this example to implement -
https://github.com/ujjwalguptaofficial/jsstore-examples/tree/master/simple_example

Basically you will have to include jsstore in your html file and create a
worker.

**Comment by dolly-chhabriya-altius** [comment]
I tried adding the script again it's giving me a same error. How to use direct file path in new Worker? Also you have mentioned that I need to create a worker so how can I do that with simple react app.

**Comment by pooja-chhabriya** [comment]
The example that you have shared is not an react js example. I want to
achieve it using simple react js.

**Comment by pooja-chhabriya** [comment]
I tried adding the script again it's giving me a same error. How to use
direct file path in new Worker? Also you have mentioned that I need to
create a worker so how can I do that with simple react app.

**Comment by ujjwalguptaofficial** [comment]
@pooja-chhabriya if you can provide me a codebase or a link to repo - then i might be able to help.

You can create a project on github and then send me a link.

**Comment by pooja-chhabriya** [comment]
Link for my repository: https://github.com/pooja-chhabriya/jsStoreExample.git

Below is the codebase:

Content of package.json

{
  "name": "@coreui/coreui-pro-react-admin-template",
  "version": "2.6.0",
  "description": "CoreUI Pro React Admin Template",
  "author": {
    "name": "Łukasz Holeczek",
    "url": "http://holeczek.pl",
    "github": "https://github.com/mrholek",
    "twitter": "https://twitter.com/lukaszholeczek"
  },
  "contributors": [
    {
      "name": "Andrzej Kopański",
      "url": "https://github.com/xidedix"
    }
  ],
  "homepage": ".",
  "copyright": "Copyright 2017-2019 creativeLabs Łukasz Holeczek",
  "license": "https://coreui.io/pro/license/",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git@github.com:coreui/coreui-pro-react-admin-template.git"
  },
  "dependencies": {
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
    "@coreui/coreui-pro": "^2.1.14",
    "@coreui/icons": "0.3.0",
    "@coreui/react": "^2.5.1",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "classnames": "^2.2.6",
    "codemirror": "^5.47.0",
    "core-js": "^3.1.4",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "flag-icon-css": "^3.3.0",
    "font-awesome": "^4.7.0",
    "formik": "^1.5.1",
    "jsstore": "^3.7.6",
    "node-sass": "^4.12.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-app-polyfill": "^1.0.1",
    "react-big-calendar": "^0.21.0",
    "react-bootstrap-table": "4.3.1",
    "react-chartjs-2": "^2.7.6",
    "react-codemirror2": "^6.0.0",
    "react-dates": "^20.2.3",
    "react-dom": "^16.8.6",
    "react-google-maps": "9.4.5",
    "react-grid-layout": "^0.16.6",
    "react-ladda": "6.0.0",
    "react-quill": "1.3.3",
    "react-router-config": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-select": "^1.3.0",
    "react-test-renderer": "^16.8.6",
    "react-text-mask-hoc": "^0.11.0",
    "react-toastify": "^5.2.1",
    "reactstrap": "^8.0.0",
    "simple-line-icons": "^2.4.1",
    "spinkit": "1.2.5",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "file-loader": "^5.1.0",
    "mutationobserver-shim": "^0.3.3",
    "react-scripts": "^3.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "test:cov": "npm test -- --coverage --watchAll=false",
    "test:debug": "react-scripts --inspect-brk test --runInBand",
    "eject": "react-scripts eject"
  },
  "bugs": {
    "url": "https://github.com/coreui/coreui-pro-react-admin-template/issues"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 10",
    "not op_mini all"
  ],
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!**/*index.js",
      "!src/serviceWorker.js",
      "!src/polyfill.js"
    ]
  },
  "engines": {
    "node": ">=8.10",
    "npm": ">=6"
  },
  "rules": {
    "import/no-webpack-loader-syntax": "off"
  }
}





content of JsStoreDemo.js where I am trying to create a connection

import React, { Component } from 'react';
import * as JsStore from 'jsstore';
/* eslint import/no-webpack-loader-syntax: off */
import * as JsStoreWorker from 'file-loader?name=scripts/[name].[hash].js!jsstore/dist/jsstore.worker.min.js';

export default class JsStoreDemo extends Component {
  
    
    initDb() {
        // const workerPath = '../Program/jsstore.worker.js';
        var jsstoreCon = new JsStore.Connection(new Worker(JsStoreWorker));
        var isDbCreated =jsstoreCon.initDb(this.getDbSchema());
        if (isDbCreated) {
            console.log('db created');
        }
        else {
            console.log('db opened');
        }
    }
    
    getDbSchema() {
        var table = {
            name: 'Student',
            columns: {
                id: {
                    primaryKey: true,
                    autoIncrement: true
                },
                name: {
                    notNull: true,
                    dataType: 'string'
                },
                gender: {
                    dataType: 'string',
                    default: 'male'
                },
                country: {
                    notNull: true,
                    dataType: 'string'
                },
                city: {
                    dataType: 'string',
                    notNull: true
                }
            }
        }
    
        var db = {
            name: 'My-Db',
            tables: [table]
        }
        return db;
    }
    


    componentDidMount() {
        console.log("in component did mount")
        this.initDb();
    }

    render() {
        return (
            <div>
               <p> Data inserted in db</p>
            </div>
        )
    }

}

**Comment by ujjwalguptaofficial** [comment]
@pooja-chhabriya can't access repository getting 404

**Comment by pooja-chhabriya** [comment]
Can you please check it now

**Comment by pooja-chhabriya** [comment]
Hi ,

Can you please check now

**Comment by ujjwalguptaofficial** [comment]
Hi 

You gotta need to find a way to create a web worker otherwise you can execute without worker by not passing worker in jsstore connection.

Take a look at this example for knowing how to use it without web worker - https://github.com/ujjwalguptaofficial/jsstore-examples/tree/master/without_web_worker

Another way is to simply create jsstore connection in your index.html file by importing all jsstore worker directly and then you can access it anywhere in your code using `window.jsstoreCon`
