### ISSUE TITLE
Without web worker example doesnt work - throws error

### ISSUE THREAD

**Issue by JavascriptRaga** [ujjwalguptaofficial/jsstore-examples#26]
Im trying to use the without web worker example but it throws error "JsStoreWorker is not defined"
below is my code (in react)
When I do 
`import JsStore from "jsstore";`
it says JsStore is undefined

and when i do
`import * as JsStore from "jsstore";
constructor() {
this.JsStore = new JsStore.Connection();
}
`

it throws web worker error

**Comment by ujjwalguptaofficial** [comment]
@JavascriptRaga you will have to expose JsStoreWorker for this. Have a look at this code - https://github.com/ujjwalguptaofficial/jsstore-examples/blob/master/typescript_without_worker/src/storage_service/idb_helper.ts#L2

When no parameter is provided, jsstore search for JsStoreWorker.

**Comment by xland** [comment]
example and doc need update
https://github.com/ujjwalguptaofficial/jsstore-examples/blob/master/simple_example/scripts/index.js
https://jsstore.net/tutorial/connection/
